---

- name: Create directory
  become: True
  file:
    path: '{{ flink_dir }}'
    state: directory
  register: flink_directory

- name: Download and extract
  become: True
  unarchive:
    src: https://archive.apache.org/dist/flink/flink-1.6.1/flink-{{ flink_version }}.tgz  #http://apache.forthnet.gr/flink/flink-1.7.2/flink-{{ flink_version }}.tgz
    dest: '{{ flink_dir }}'
    remote_src: True
    owner: '{{ remote_user }}'
    group: '{{ remote_user }}'
    extra_opts: [--strip-components=1] # remove the top level directory
  when: flink_directory.changed

- name: Apply configuration
  template:
    src: '{{ item }}.j2'
    dest: '{{ flink_dir }}/conf/{{ item }}'
  with_items:
    - flink-conf.yaml
    - slaves
    - log4j.properties

- name: Start master
  include_tasks: systemd_jobmanager.yml
  when: flink_type == "master"

- name: Start slaves
  include_tasks: systemd_taskmanager.yml
  when: flink_type == "slave"
