---

- name: Install systemd unit
  become: True
  template:
    src: kafka.service.j2
    dest: /etc/systemd/system/kafka.service
    mode: 0644

- name: Launch Kafka
  become: True
  systemd:
    name: kafka
    state: started
    daemon_reload: True
    enabled: '{{ kafka_enable_services }}'
